version: "3.5"
services:
  centos7imagick:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
  centos7imagickrel:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      dockerfile: Dockerfile.rel
  centos6imagick:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm6:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: 6

volumes:
  rpms:
    name: rpms
  rpm6:
    name: rpm6
  rpm7:
    name: rpm7
